// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: app/api/p2p.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	blc "bigcat_test_coin/app/blc"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//P2P通讯协议
type N2PGetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchHeight int64 `protobuf:"varint,1,opt,name=search_height,json=searchHeight,proto3" json:"search_height,omitempty"`
}

func (x *N2PGetInfo) Reset() {
	*x = N2PGetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *N2PGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2PGetInfo) ProtoMessage() {}

func (x *N2PGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2PGetInfo.ProtoReflect.Descriptor instead.
func (*N2PGetInfo) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{0}
}

func (x *N2PGetInfo) GetSearchHeight() int64 {
	if x != nil {
		return x.SearchHeight
	}
	return 0
}

type P2NGetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height        int64  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	LeftHash      []byte `protobuf:"bytes,2,opt,name=left_hash,json=leftHash,proto3" json:"left_hash,omitempty"`
	LastHash      []byte `protobuf:"bytes,3,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
	SearchHash    []byte `protobuf:"bytes,4,opt,name=search_hash,json=searchHash,proto3" json:"search_hash,omitempty"`
	VerifierTotal int64  `protobuf:"varint,5,opt,name=verifier_total,json=verifierTotal,proto3" json:"verifier_total,omitempty"`
	Now           int64  `protobuf:"varint,6,opt,name=now,proto3" json:"now,omitempty"`
}

func (x *P2NGetInfo) Reset() {
	*x = P2NGetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P2NGetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2NGetInfo) ProtoMessage() {}

func (x *P2NGetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2NGetInfo.ProtoReflect.Descriptor instead.
func (*P2NGetInfo) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{1}
}

func (x *P2NGetInfo) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *P2NGetInfo) GetLeftHash() []byte {
	if x != nil {
		return x.LeftHash
	}
	return nil
}

func (x *P2NGetInfo) GetLastHash() []byte {
	if x != nil {
		return x.LastHash
	}
	return nil
}

func (x *P2NGetInfo) GetSearchHash() []byte {
	if x != nil {
		return x.SearchHash
	}
	return nil
}

func (x *P2NGetInfo) GetVerifierTotal() int64 {
	if x != nil {
		return x.VerifierTotal
	}
	return 0
}

func (x *P2NGetInfo) GetNow() int64 {
	if x != nil {
		return x.Now
	}
	return 0
}

type N2PGetBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftHeight  int64  `protobuf:"varint,1,opt,name=left_height,json=leftHeight,proto3" json:"left_height,omitempty"`
	RightHeight int64  `protobuf:"varint,2,opt,name=right_height,json=rightHeight,proto3" json:"right_height,omitempty"`
	LastHash    []byte `protobuf:"bytes,3,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
}

func (x *N2PGetBlock) Reset() {
	*x = N2PGetBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *N2PGetBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2PGetBlock) ProtoMessage() {}

func (x *N2PGetBlock) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2PGetBlock.ProtoReflect.Descriptor instead.
func (*N2PGetBlock) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{2}
}

func (x *N2PGetBlock) GetLeftHeight() int64 {
	if x != nil {
		return x.LeftHeight
	}
	return 0
}

func (x *N2PGetBlock) GetRightHeight() int64 {
	if x != nil {
		return x.RightHeight
	}
	return 0
}

func (x *N2PGetBlock) GetLastHash() []byte {
	if x != nil {
		return x.LastHash
	}
	return nil
}

type N2PGetBlocksHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeftHeight int64    `protobuf:"varint,1,opt,name=left_height,json=leftHeight,proto3" json:"left_height,omitempty"`
	BlockTxs   [][]byte `protobuf:"bytes,2,rep,name=block_txs,json=blockTxs,proto3" json:"block_txs,omitempty"`
}

func (x *N2PGetBlocksHash) Reset() {
	*x = N2PGetBlocksHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *N2PGetBlocksHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*N2PGetBlocksHash) ProtoMessage() {}

func (x *N2PGetBlocksHash) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use N2PGetBlocksHash.ProtoReflect.Descriptor instead.
func (*N2PGetBlocksHash) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{3}
}

func (x *N2PGetBlocksHash) GetLeftHeight() int64 {
	if x != nil {
		return x.LeftHeight
	}
	return 0
}

func (x *N2PGetBlocksHash) GetBlockTxs() [][]byte {
	if x != nil {
		return x.BlockTxs
	}
	return nil
}

type P2NGetBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*blc.Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *P2NGetBlock) Reset() {
	*x = P2NGetBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *P2NGetBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*P2NGetBlock) ProtoMessage() {}

func (x *P2NGetBlock) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use P2NGetBlock.ProtoReflect.Descriptor instead.
func (*P2NGetBlock) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{4}
}

func (x *P2NGetBlock) GetBlocks() []*blc.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type PushBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Block *blc.Block `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *PushBlock) Reset() {
	*x = PushBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushBlock) ProtoMessage() {}

func (x *PushBlock) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushBlock.ProtoReflect.Descriptor instead.
func (*PushBlock) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{5}
}

func (x *PushBlock) GetBlock() *blc.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

type PlushVerifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verifier *blc.Verifier `protobuf:"bytes,1,opt,name=verifier,proto3" json:"verifier,omitempty"`
}

func (x *PlushVerifier) Reset() {
	*x = PlushVerifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlushVerifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlushVerifier) ProtoMessage() {}

func (x *PlushVerifier) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlushVerifier.ProtoReflect.Descriptor instead.
func (*PlushVerifier) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{6}
}

func (x *PlushVerifier) GetVerifier() *blc.Verifier {
	if x != nil {
		return x.Verifier
	}
	return nil
}

type PushContracts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conts []*blc.Cont `protobuf:"bytes,1,rep,name=conts,proto3" json:"conts,omitempty"`
}

func (x *PushContracts) Reset() {
	*x = PushContracts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushContracts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushContracts) ProtoMessage() {}

func (x *PushContracts) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushContracts.ProtoReflect.Descriptor instead.
func (*PushContracts) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{7}
}

func (x *PushContracts) GetConts() []*blc.Cont {
	if x != nil {
		return x.Conts
	}
	return nil
}

type PushTransactions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Trans []*blc.Transaction `protobuf:"bytes,1,rep,name=trans,proto3" json:"trans,omitempty"`
}

func (x *PushTransactions) Reset() {
	*x = PushTransactions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_p2p_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTransactions) ProtoMessage() {}

func (x *PushTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_p2p_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTransactions.ProtoReflect.Descriptor instead.
func (*PushTransactions) Descriptor() ([]byte, []int) {
	return file_app_api_p2p_proto_rawDescGZIP(), []int{8}
}

func (x *PushTransactions) GetTrans() []*blc.Transaction {
	if x != nil {
		return x.Trans
	}
	return nil
}

var File_app_api_p2p_proto protoreflect.FileDescriptor

var file_app_api_p2p_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x32, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x32, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x11, 0x61, 0x70, 0x70,
	0x2f, 0x62, 0x6c, 0x63, 0x2f, 0x62, 0x6c, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31,
	0x0a, 0x0a, 0x4e, 0x32, 0x50, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x22, 0xb8, 0x01, 0x0a, 0x0a, 0x50, 0x32, 0x4e, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x65, 0x66, 0x74,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6c, 0x65, 0x66,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x5f,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x6f,
	0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x6f, 0x77, 0x22, 0x6e, 0x0a, 0x0b,
	0x4e, 0x32, 0x50, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1f, 0x0a, 0x0b, 0x6c,
	0x65, 0x66, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x6c, 0x65, 0x66, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0x50, 0x0a, 0x10,
	0x4e, 0x32, 0x50, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x65, 0x66, 0x74, 0x48, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x74, 0x78, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x78, 0x73, 0x22, 0x31,
	0x0a, 0x0b, 0x50, 0x32, 0x4e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x22, 0x0a,
	0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x62, 0x6c, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x73, 0x22, 0x2d, 0x0a, 0x09, 0x50, 0x75, 0x73, 0x68, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x20,
	0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x62, 0x6c, 0x63, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x22, 0x3a, 0x0a, 0x0d, 0x50, 0x6c, 0x75, 0x73, 0x68, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x12, 0x29, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x6c, 0x63, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x0d,
	0x50, 0x75, 0x73, 0x68, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x12, 0x1f, 0x0a,
	0x05, 0x63, 0x6f, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x62,
	0x6c, 0x63, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x52, 0x05, 0x63, 0x6f, 0x6e, 0x74, 0x73, 0x22, 0x3a,
	0x0a, 0x10, 0x50, 0x75, 0x73, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x26, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x62, 0x6c, 0x63, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x05, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x42, 0x38, 0x0a, 0x16, 0x64, 0x65,
	0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74, 0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x69,
	0x6e, 0x2e, 0x76, 0x31, 0x42, 0x06, 0x41, 0x64, 0x64, 0x72, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x14,
	0x6e, 0x65, 0x77, 0x73, 0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x32,
	0x70, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_api_p2p_proto_rawDescOnce sync.Once
	file_app_api_p2p_proto_rawDescData = file_app_api_p2p_proto_rawDesc
)

func file_app_api_p2p_proto_rawDescGZIP() []byte {
	file_app_api_p2p_proto_rawDescOnce.Do(func() {
		file_app_api_p2p_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_api_p2p_proto_rawDescData)
	})
	return file_app_api_p2p_proto_rawDescData
}

var file_app_api_p2p_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_app_api_p2p_proto_goTypes = []interface{}{
	(*N2PGetInfo)(nil),       // 0: p2p.v1.N2PGetInfo
	(*P2NGetInfo)(nil),       // 1: p2p.v1.P2NGetInfo
	(*N2PGetBlock)(nil),      // 2: p2p.v1.N2PGetBlock
	(*N2PGetBlocksHash)(nil), // 3: p2p.v1.N2PGetBlocksHash
	(*P2NGetBlock)(nil),      // 4: p2p.v1.P2NGetBlock
	(*PushBlock)(nil),        // 5: p2p.v1.PushBlock
	(*PlushVerifier)(nil),    // 6: p2p.v1.PlushVerifier
	(*PushContracts)(nil),    // 7: p2p.v1.PushContracts
	(*PushTransactions)(nil), // 8: p2p.v1.PushTransactions
	(*blc.Block)(nil),        // 9: blc.Block
	(*blc.Verifier)(nil),     // 10: blc.Verifier
	(*blc.Cont)(nil),         // 11: blc.Cont
	(*blc.Transaction)(nil),  // 12: blc.Transaction
}
var file_app_api_p2p_proto_depIdxs = []int32{
	9,  // 0: p2p.v1.P2NGetBlock.blocks:type_name -> blc.Block
	9,  // 1: p2p.v1.PushBlock.block:type_name -> blc.Block
	10, // 2: p2p.v1.PlushVerifier.verifier:type_name -> blc.Verifier
	11, // 3: p2p.v1.PushContracts.conts:type_name -> blc.Cont
	12, // 4: p2p.v1.PushTransactions.trans:type_name -> blc.Transaction
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_app_api_p2p_proto_init() }
func file_app_api_p2p_proto_init() {
	if File_app_api_p2p_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_api_p2p_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*N2PGetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P2NGetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*N2PGetBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*N2PGetBlocksHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*P2NGetBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlushVerifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushContracts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_p2p_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushTransactions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_api_p2p_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_api_p2p_proto_goTypes,
		DependencyIndexes: file_app_api_p2p_proto_depIdxs,
		MessageInfos:      file_app_api_p2p_proto_msgTypes,
	}.Build()
	File_app_api_p2p_proto = out.File
	file_app_api_p2p_proto_rawDesc = nil
	file_app_api_p2p_proto_goTypes = nil
	file_app_api_p2p_proto_depIdxs = nil
}
