// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: app/api/contapi/source.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	contract "bigcat_test_coin/app/blc/contract"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *SourceRequest) Reset() {
	*x = SourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_contapi_source_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceRequest) ProtoMessage() {}

func (x *SourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_contapi_source_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceRequest.ProtoReflect.Descriptor instead.
func (*SourceRequest) Descriptor() ([]byte, []int) {
	return file_app_api_contapi_source_proto_rawDescGZIP(), []int{0}
}

func (x *SourceRequest) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

type SourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *contract.Source `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *SourceReply) Reset() {
	*x = SourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_contapi_source_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceReply) ProtoMessage() {}

func (x *SourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_contapi_source_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceReply.ProtoReflect.Descriptor instead.
func (*SourceReply) Descriptor() ([]byte, []int) {
	return file_app_api_contapi_source_proto_rawDescGZIP(), []int{1}
}

func (x *SourceReply) GetSource() *contract.Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type SourceChainRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tx string `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
}

func (x *SourceChainRequest) Reset() {
	*x = SourceChainRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_contapi_source_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceChainRequest) ProtoMessage() {}

func (x *SourceChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_contapi_source_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceChainRequest.ProtoReflect.Descriptor instead.
func (*SourceChainRequest) Descriptor() ([]byte, []int) {
	return file_app_api_contapi_source_proto_rawDescGZIP(), []int{2}
}

func (x *SourceChainRequest) GetTx() string {
	if x != nil {
		return x.Tx
	}
	return ""
}

type SourceChainReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sources []*contract.Source `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
}

func (x *SourceChainReply) Reset() {
	*x = SourceChainReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_contapi_source_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SourceChainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceChainReply) ProtoMessage() {}

func (x *SourceChainReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_contapi_source_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceChainReply.ProtoReflect.Descriptor instead.
func (*SourceChainReply) Descriptor() ([]byte, []int) {
	return file_app_api_contapi_source_proto_rawDescGZIP(), []int{3}
}

func (x *SourceChainReply) GetSources() []*contract.Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

type CreateSourceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Private string           `protobuf:"bytes,1,opt,name=private,proto3" json:"private,omitempty"`
	Source  *contract.Source `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *CreateSourceRequest) Reset() {
	*x = CreateSourceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_contapi_source_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceRequest) ProtoMessage() {}

func (x *CreateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_contapi_source_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateSourceRequest) Descriptor() ([]byte, []int) {
	return file_app_api_contapi_source_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSourceRequest) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

func (x *CreateSourceRequest) GetSource() *contract.Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type CreateSourceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Hx  string `protobuf:"bytes,2,opt,name=hx,proto3" json:"hx,omitempty"`
}

func (x *CreateSourceReply) Reset() {
	*x = CreateSourceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_api_contapi_source_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSourceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceReply) ProtoMessage() {}

func (x *CreateSourceReply) ProtoReflect() protoreflect.Message {
	mi := &file_app_api_contapi_source_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceReply.ProtoReflect.Descriptor instead.
func (*CreateSourceReply) Descriptor() ([]byte, []int) {
	return file_app_api_contapi_source_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSourceReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateSourceReply) GetHx() string {
	if x != nil {
		return x.Hx
	}
	return ""
}

var File_app_api_contapi_source_proto protoreflect.FileDescriptor

var file_app_api_contapi_source_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x70, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x61, 0x70, 0x70, 0x2f, 0x62, 0x6c, 0x63, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1f, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x74, 0x78, 0x22, 0x37, 0x0a, 0x0b, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22,
	0x24, 0x0a, 0x12, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x78, 0x22, 0x3e, 0x0a, 0x10, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x07, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x59, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x22, 0x35, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x78, 0x32, 0x9a, 0x02, 0x0a, 0x0d, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x4d, 0x0a, 0x09, 0x53, 0x61, 0x79,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x2f, 0x7b, 0x74, 0x78, 0x7d, 0x12, 0x5b, 0x0a, 0x0e, 0x53, 0x61, 0x79, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x7b, 0x74, 0x78, 0x7d, 0x12, 0x5d, 0x0a, 0x0f, 0x53, 0x61, 0x79, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x22, 0x07, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x3a, 0x01, 0x2a, 0x42, 0x44, 0x0a, 0x16, 0x64, 0x65, 0x76, 0x2e, 0x6b, 0x72, 0x61, 0x74,
	0x6f, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x08,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x1e, 0x6e, 0x65, 0x77, 0x73,
	0x5f, 0x63, 0x6f, 0x69, 0x6e, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_app_api_contapi_source_proto_rawDescOnce sync.Once
	file_app_api_contapi_source_proto_rawDescData = file_app_api_contapi_source_proto_rawDesc
)

func file_app_api_contapi_source_proto_rawDescGZIP() []byte {
	file_app_api_contapi_source_proto_rawDescOnce.Do(func() {
		file_app_api_contapi_source_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_api_contapi_source_proto_rawDescData)
	})
	return file_app_api_contapi_source_proto_rawDescData
}

var file_app_api_contapi_source_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_api_contapi_source_proto_goTypes = []interface{}{
	(*SourceRequest)(nil),       // 0: pro.v1.SourceRequest
	(*SourceReply)(nil),         // 1: pro.v1.SourceReply
	(*SourceChainRequest)(nil),  // 2: pro.v1.SourceChainRequest
	(*SourceChainReply)(nil),    // 3: pro.v1.SourceChainReply
	(*CreateSourceRequest)(nil), // 4: pro.v1.CreateSourceRequest
	(*CreateSourceReply)(nil),   // 5: pro.v1.CreateSourceReply
	(*contract.Source)(nil),     // 6: contract.source
}
var file_app_api_contapi_source_proto_depIdxs = []int32{
	6, // 0: pro.v1.SourceReply.source:type_name -> contract.source
	6, // 1: pro.v1.SourceChainReply.sources:type_name -> contract.source
	6, // 2: pro.v1.CreateSourceRequest.source:type_name -> contract.source
	0, // 3: pro.v1.SourceGreeter.SaySource:input_type -> pro.v1.SourceRequest
	2, // 4: pro.v1.SourceGreeter.SayChainSource:input_type -> pro.v1.SourceChainRequest
	4, // 5: pro.v1.SourceGreeter.SayCreateSource:input_type -> pro.v1.CreateSourceRequest
	1, // 6: pro.v1.SourceGreeter.SaySource:output_type -> pro.v1.SourceReply
	3, // 7: pro.v1.SourceGreeter.SayChainSource:output_type -> pro.v1.SourceChainReply
	5, // 8: pro.v1.SourceGreeter.SayCreateSource:output_type -> pro.v1.CreateSourceReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_app_api_contapi_source_proto_init() }
func file_app_api_contapi_source_proto_init() {
	if File_app_api_contapi_source_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_api_contapi_source_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_contapi_source_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_contapi_source_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceChainRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_contapi_source_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SourceChainReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_contapi_source_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSourceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_api_contapi_source_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSourceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_api_contapi_source_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_api_contapi_source_proto_goTypes,
		DependencyIndexes: file_app_api_contapi_source_proto_depIdxs,
		MessageInfos:      file_app_api_contapi_source_proto_msgTypes,
	}.Build()
	File_app_api_contapi_source_proto = out.File
	file_app_api_contapi_source_proto_rawDesc = nil
	file_app_api_contapi_source_proto_goTypes = nil
	file_app_api_contapi_source_proto_depIdxs = nil
}
